name: Update Project lists
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Permite l'esecuzione manuale
  schedule:
    - cron: '0 0 * * *'  # Esecuzione giornaliera

jobs:
  update-lists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install tree (optional su ubuntu-latest)
        run: |
          sudo apt-get update
          sudo apt-get install -y tree

      - name: Generate tree lists
        run: |
          tree src/ > lists.txt

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update project lists"
          branch: main
          file_pattern: lists.txt